### ISSUE TITLE
Add QR code scanner in Android Studio

### ISSUE THREAD

**Issue by FaizaAmjad** [DIT113-V22/group-07#101]
As an app user, I want to be able to scan the QR codes on the objects displayed in the world so that i can learn more information about waste.

Acceptance criteria:
- Uses the camera to scan the object. 
- Configure code with Kotlin.
- User tab the button to scan the QR code.
- User gets search results after scanning.

**Comment by Adrianmeda** [comment]
After thorough research, the group has chosen to close this issue because we consider it to be outside our scope right now.

**Comment by FaizaAmjad** [comment]
Hence we are unable to use the camera in emulator. We decided to implement a google search system as a result of scanning. In that way the user can get the information about objects in a search result through app.

**Comment by Toerngren** [comment]
Re-closing this issue.

**Comment by FaizaAmjad** [comment]
Team decided to reduce the scope and not include scanning feature in the app. Decision date: 2022-05-20
Reason: Real mobile devices need to be used in order to scan.
