### ISSUE TITLE
Toggle semi-autonomous driving on and off

### ISSUE THREAD

**Issue by Adrianmeda** [DIT113-V22/group-07#109]
As a user I want to be able to control the garbage truck without the assist of semi-autonomous driving mode enabled. So that I can go real close quarters with obstacles and not having the truck turning.

Acceptance criteria:
- [ ] The app has a toggle on/off display.
- [ ] Arduino boolean for when the truck should loop the obstacleAvoid() or not.

**Comment by FaizaAmjad** [comment]
Opening Issue to enhance the presentation of the button in the app.
