### ISSUE TITLE
Cruise Control

### ISSUE THREAD

**Issue by FaizaAmjad** [DIT113-V22/group-07#11]
**User Story:**
As a middle aged person I want to be able to drive the vehicle without holding down the button manually so that I can comfortably drive around and manoeuvre better.

**Acceptance Criteria:**

- The vehicle can go forward in a semi-autonomous mode without the user having to hold accelerate.

**Comment by Toerngren** [comment]
Moved to Sprint 2.

**Comment by FaizaAmjad** [comment]
Truck can move either by a single click on keyboard keys or navigations buttons via app without pressing them continuously.
