### ISSUE TITLE
JoyStick App

### ISSUE THREAD

**Issue by gusandchbh** [DIT113-V22/group-07#24]
**User Story:**
As an application player I want to be able to use a joystick controller on the app to control the vehicle so that I can have an improved driving experience.

**Acceptance Criteria:**

- The controller is connected to the app.
- The vehicle can be controlled using app joystick controller.
- The controller is tested.

**Comment by ghost** [comment]
This was later removed from the app, due to problem with steering. App is currently using navigation buttons.
