### ISSUE TITLE
Basic obstacle avoidance 

### ISSUE THREAD

**Issue by Adrianmeda** [DIT113-V22/group-07#27]
As a truck driver I want the car to recognise obstacles when going forward and auto brake before it hits them, so that I don’t crash the car nor cause damage.

**Acceptance Criteria:**
- The vehicle can auto-brake and detect obstacles.
- The auto-brake system is tested.

**Comment by umairngo** [comment]
#33 
Issue is closed

**Comment by umairngo** [comment]
#33
Issue is closed
