### ISSUE TITLE
Educational Context

### ISSUE THREAD

**Issue by gusciuag** [DIT113-V22/group-07#29]
**User Story:**
As a gamer, I want to learn valuable educational context, so that I can benefit from learning about the environment when playing the game. 

**Acceptance criteria:**

- Gamers learn adequate knowledge of the environment throughout the game.
- Gamers learn adequate knowledge of the environment on intro page in app.

**Comment by FaizaAmjad** [comment]
Got some problems to run mods in SMCE after implementing the text display in the game. Implementation of the text display can be seen in a separate branch   [dialog_box](https://github.com/DIT113-V22/group-07/tree/dialog_box)

https://user-images.githubusercontent.com/102183756/168249229-0454722d-ca17-494c-acca-773c989cd464.mp4
